services:
  tpr-generator:
    image: tpr-generator:${TPR_IMAGE_VERSION}
    ports:
      - '${HOST_PORT:-2999}:3000'
    volumes:
      - tpr-generator-data:${TPR_ROOT_VOLUME_PATH}
    secrets:
      - abc_secret

volumes:
  tpr-generator-data:
    driver: local

secrets:
  abc_secret:
    file: ./secrets/abc.txt
    name: abc_secret-${ABC_HASH}
