services:
  tpr-generator:
    build:
      context: .
    image: tpr-generator:${TPR_IMAGE_VERSION}
    ports:
      - '${HOST_PORT:-2999}:3000'
    volumes:
      - tpr-generator-data:${TPR_ROOT_VOLUME_PATH}

volumes:
  tpr-generator-data:
    driver: local
