// check Id is an enum of numbers

// checkId to string name

//

export enum CheckId {
  Invalid = -1,
  Palace_of_Twilight_East_Wing_Second_Room_Southwest_Chest = 0,
  Faron_Field_Poe = 1,
  Goron_Mines_Crystal_Switch_Room_Small_Chest = 2,
  Goron_Mines_Gor_Liggs_Key_Shard = 3,
  Wrestling_With_Bo = 4,
  Goron_Mines_After_Crystal_Switch_Room_Magnet_Wall_Chest = 5,
  Agitha_Female_Phasmid_Reward = 6,
  Snowpeak_Ruins_East_Courtyard_Buried_Chest = 7,
  Snowpeak_Ruins_Lobby_East_Armor_Chest = 8,
  Bridge_of_Eldin_Owl_Statue_Sky_Character = 9,
  Arbiters_Grounds_Entrance_Chest = 10,
  Hyrule_Castle_Treasure_Room_Third_Chest = 11,
  Arbiters_Grounds_Torch_Room_Poe = 12,
  Palace_of_Twilight_East_Wing_Second_Room_Northwest_Chest = 13,
  Hyrule_Castle_Graveyard_Owl_Statue_Chest = 14,
  Faron_Field_Corner_Grotto_Rear_Chest = 15,
  Zoras_Domain_Male_Dragonfly = 16,
  Gerudo_Desert_Lone_Small_Chest = 17,
  Gerudo_Desert_Rock_Grotto_Lantern_Chest = 18,
  Lake_Hylia_Water_Toadpoli_Grotto_Chest = 19,
  Faron_Mist_Stump_Chest = 20,
  Lanayru_Field_Poe_Grotto_Left_Poe = 21,
  City_in_The_Sky_Underwater_West_Chest = 22,
  Temple_of_Time_Dungeon_Reward = 23,
  Ordon_Spring_Golden_Wolf = 24,
  Hyrule_Castle_Main_Hall_Northeast_Chest = 25,
  Gerudo_Desert_Northeast_Chest_Behind_Gates = 26,
  Ilia_Charm = 27,
  Agitha_Male_Ladybug_Reward = 28,
  Hyrule_Castle_Treasure_Room_Seventh_Small_Chest = 29,
  Lake_Hylia_Tower_Poe = 30,
  Arbiters_Grounds_Spinner_Room_Lower_North_Chest = 31,
  Sacred_Grove_Past_Owl_Statue_Chest = 32,
  Lakebed_Temple_Morpheel_Heart_Container = 33,
  Lost_Woods_Lantern_Chest = 34,
  Lanayru_Field_Skulltula_Grotto_Chest = 35,
  Faron_Mist_Cave_Lantern_Chest = 36,
  Eldin_Lantern_Cave_First_Chest = 37,
  Faron_Field_Corner_Grotto_Right_Chest = 38,
  Ordon_Ranch_Grotto_Lantern_Chest = 39,
  Sera_Shop_Slingshot = 40,
  Lakebed_Temple_East_Lower_Waterwheel_Stalactite_Chest = 41,
  Snowpeak_Ruins_Chest_After_Darkhammer = 42,
  Goron_Mines_Gor_Liggs_Chest = 43,
  Arbiters_Grounds_East_Turning_Room_Poe = 44,
  Lanayru_Field_Female_Stag_Beetle = 45,
  Zoras_Domain_Chest_By_Mother_and_Child_Isles = 46,
  North_Faron_Woods_Deku_Baba_Chest = 47,
  City_in_The_Sky_Baba_Tower_Top_Small_Chest = 48,
  Kakariko_Village_Bomb_Rock_Spire_Heart_Piece = 49,
  Arbiters_Grounds_Stallord_Heart_Container = 50,
  Zoras_Domain_Chest_Behind_Waterfall = 51,
  City_in_The_Sky_Central_Outside_Ledge_Chest = 52,
  Palace_of_Twilight_East_Wing_First_Room_West_Alcove = 53,
  Bulblin_Camp_First_Chest_Under_Tower_At_Entrance = 54,
  Arbiters_Grounds_West_Stalfos_Northeast_Chest = 55,
  Outside_South_Castle_Town_Male_Ladybug = 56,
  Jovani_20_Poe_Soul_Reward = 57,
  West_Hyrule_Field_Helmasaur_Grotto_Chest = 58,
  Zoras_Domain_Underwater_Goron = 59,
  Kakariko_Inn_Chest = 60,
  Agitha_Female_Beetle_Reward = 61,
  Lanayru_Spring_Back_Room_Left_Chest = 62,
  Agitha_Female_Grasshopper_Reward = 63,
  City_in_The_Sky_Baba_Tower_Alcove_Chest = 64,
  Goron_Mines_Gor_Amato_Chest = 65,
  Goron_Mines_Gor_Ebizo_Chest = 66,
  Faron_Mist_North_Chest = 67,
  Lakebed_Temple_West_Lower_Small_Chest = 68,
  Agitha_Male_Phasmid_Reward = 69,
  City_in_The_Sky_Chest_Behind_North_Fan = 70,
  Lake_Lantern_Cave_Final_Poe = 71,
  Temple_of_Time_Lobby_Lantern_Chest = 72,
  Lakebed_Temple_East_Second_Floor_Southeast_Chest = 73,
  Hyrule_Field_Amphitheater_Poe = 74,
  Gerudo_Desert_Peahat_Ledge_Chest = 75,
  Iza_Helping_Hand = 76,
  Lake_Lantern_Cave_Second_Chest = 77,
  Lakebed_Temple_Central_Room_Small_Chest = 78,
  Links_Basement_Chest = 79,
  Snowpeak_Cave_Ice_Lantern_Chest = 80,
  Gerudo_Desert_Poe_Above_Cave_of_Ordeals = 81,
  Eldin_Field_Water_Bomb_Fish_Grotto_Chest = 82,
  Kakariko_Village_Watchtower_Poe = 83,
  Agitha_Female_Dragonfly_Reward = 84,
  Gift_From_Ralis = 85,
  South_Faron_Cave_Chest = 86,
  Lakebed_Temple_West_Second_Floor_Southeast_Chest = 87,
  Temple_of_Time_Darknut_Chest = 88,
  Forest_Temple_Central_North_Chest = 89,
  Lanayru_Field_Male_Stag_Beetle = 90,
  City_in_The_Sky_Underwater_East_Chest = 91,
  Forest_Temple_East_Water_Cave_Chest = 92,
  Hyrule_Castle_Treasure_Room_Second_Small_Chest = 93,
  Lake_Hylia_Bridge_Vines_Chest = 94,
  City_in_The_Sky_East_Wing_After_Dinalfos_Ledge_Chest = 95,
  Snowpeak_Ruins_Lobby_Armor_Poe = 96,
  Faron_Field_Tree_Heart_Piece = 97,
  Eldin_Field_Stalfos_Grotto_Right_Small_Chest = 98,
  Lake_Lantern_Cave_First_Poe = 99,
  Hyrule_Castle_Treasure_Room_Fourth_Small_Chest = 100,
  Kakariko_Village_Malo_Mart_Hawkeye = 101,
  Uli_Cradle_Delivery = 102,
  Flight_By_Fowl_Ledge_Poe = 103,
  Lakebed_Temple_West_Water_Supply_Chest = 104,
  Palace_of_Twilight_East_Wing_Second_Room_Northeast_Chest = 105,
  Kakariko_Village_Bomb_Shop_Poe = 106,
  Faron_Mist_Poe = 107,
  Lake_Hylia_Bridge_Cliff_Poe = 108,
  Hyrule_Castle_Main_Hall_Southwest_Chest = 109,
  Wooden_Sword_Chest = 110,
  Goron_Mines_Dangoro_Chest = 111,
  City_in_The_Sky_Garden_Island_Poe = 112,
  Faron_Field_Female_Beetle = 113,
  Eldin_Field_Male_Grasshopper = 114,
  Gerudo_Desert_Rock_Grotto_First_Poe = 115,
  Eldin_Lantern_Cave_Second_Chest = 116,
  Palace_of_Twilight_West_Wing_Second_Room_Southeast_Chest = 117,
  Arbiters_Grounds_East_Upper_Turnable_Redead_Chest = 118,
  Sacred_Grove_Temple_of_Time_Owl_Statue_Poe = 119,
  Forest_Temple_West_Tile_Worm_Room_Vines_Chest = 120,
  Agitha_Male_Dragonfly_Reward = 121,
  City_in_The_Sky_East_Tile_Worm_Small_Chest = 122,
  Palace_of_Twilight_Central_Tower_Chest = 123,
  Outside_Arbiters_Grounds_Poe = 124,
  Outside_South_Castle_Town_Double_Clawshot_Chasm_Chest = 125,
  Hyrule_Field_Amphitheater_Owl_Statue_Chest = 126,
  Snowpeak_Ruins_Northeast_Chandelier_Chest = 127,
  Hyrule_Castle_West_Courtyard_North_Small_Chest = 128,
  Agitha_Female_Stag_Beetle_Reward = 129,
  Lakebed_Temple_West_Second_Floor_Central_Small_Chest = 130,
  Agitha_Female_Mantis_Reward = 131,
  Lakebed_Temple_Lobby_Rear_Chest = 132,
  Bridge_of_Eldin_Owl_Statue_Chest = 133,
  West_Hyrule_Field_Golden_Wolf = 134,
  Lake_Hylia_Bridge_Cliff_Chest = 135,
  City_in_The_Sky_West_Garden_Lower_Chest = 136,
  Goron_Mines_Outside_Clawshot_Chest = 137,
  Lake_Lantern_Cave_Fifth_Chest = 138,
  Palace_of_Twilight_Big_Key_Chest = 139,
  Agitha_Male_Beetle_Reward = 140,
  Gerudo_Desert_Campfire_East_Chest = 141,
  Hyrule_Castle_Big_Key_Chest = 142,
  Temple_of_Time_Moving_Wall_Beamos_Room_Chest = 143,
  Lake_Lantern_Cave_Fourth_Chest = 144,
  Lakebed_Temple_East_Lower_Waterwheel_Bridge_Chest = 145,
  City_in_The_Sky_East_First_Wing_Chest_After_Fans = 146,
  Lake_Lantern_Cave_Tenth_Chest = 147,
  Lake_Lantern_Cave_Ninth_Chest = 148,
  Kakariko_Watchtower_Alcove_Chest = 149,
  West_Hyrule_Field_Male_Butterfly = 150,
  Hyrule_Castle_King_Bulblin_Key = 151,
  Hyrule_Castle_East_Wing_Boomerang_Puzzle_Chest = 152,
  Palace_of_Twilight_Central_Outdoor_Chest = 153,
  Hyrule_Castle_Treasure_Room_First_Small_Chest = 154,
  Goron_Mines_Outside_Underwater_Chest = 155,
  Lake_Lantern_Cave_Eleventh_Chest = 156,
  Agitha_Female_Ant_Reward = 157,
  Cave_of_Ordeals_Great_Fairy_Reward = 158,
  Forest_Temple_Central_Chest_Hanging_From_Web = 159,
  Lost_Woods_Waterfall_Poe = 160,
  Kakariko_Graveyard_Open_Poe = 161,
  Eldin_Field_Bomskit_Grotto_Left_Chest = 162,
  Hyrule_Castle_West_Courtyard_Central_Small_Chest = 163,
  City_in_The_Sky_West_Wing_Narrow_Ledge_Chest = 164,
  Snowpeak_Ruins_Ordon_Pumpkin_Chest = 165,
  Skybook_From_Impaz = 166,
  STAR_Prize_1 = 167,
  Hyrule_Castle_Treasure_Room_Fifth_Chest = 168,
  Zoras_Domain_Mother_and_Child_Isle_Poe = 169,
  Ordon_Shield = 170,
  Flight_By_Fowl_Fourth_Platform_Chest = 171,
  Goron_Springwater_Rush = 172,
  Arbiters_Grounds_Hidden_Wall_Poe = 173,
  Agitha_Female_Dayfly_Reward = 174,
  Outside_South_Castle_Town_Tightrope_Chest = 175,
  Lake_Hylia_Bridge_Bubble_Grotto_Chest = 176,
  Hyrule_Castle_Main_Hall_Northwest_Chest = 177,
  Snowpeak_Ruins_Ice_Room_Poe = 178,
  Forest_Temple_Dungeon_Reward = 179,
  Arbiters_Grounds_Spinner_Room_Lower_Central_Small_Chest = 180,
  Hyrule_Castle_Treasure_Room_Fifth_Small_Chest = 181,
  Goron_Mines_Chest_Before_Dangoro = 182,
  Agitha_Male_Snail_Reward = 183,
  Agitha_Male_Ant_Reward = 184,
  Lakebed_Temple_Before_Deku_Toad_Underwater_Left_Chest = 185,
  Temple_of_Time_Poe_Above_Scales = 186,
  Forest_Temple_North_Deku_Like_Chest = 187,
  Lakebed_Temple_Central_Room_Chest = 188,
  Temple_of_Time_First_Staircase_Gohma_Gate_Chest = 189,
  Temple_of_Time_First_Staircase_Window_Chest = 190,
  Forest_Temple_Totem_Pole_Chest = 191,
  Faron_Mist_South_Chest = 192,
  Lake_Lantern_Cave_Eighth_Chest = 193,
  Snowpeak_Ruins_Lobby_Chandelier_Chest = 194,
  Lakebed_Temple_Deku_Toad_Chest = 195,
  Lake_Hylia_Dock_Poe = 196,
  Lake_Hylia_Shell_Blade_Grotto_Chest = 197,
  Forest_Temple_West_Tile_Worm_Chest_Behind_Stairs = 198,
  Renados_Letter = 199,
  Lake_Lantern_Cave_Thirteenth_Chest = 200,
  Arbiters_Grounds_Spinner_Room_First_Small_Chest = 201,
  Palace_of_Twilight_Collect_Both_Sols = 202,
  Upper_Zoras_River_Female_Dragonfly = 203,
  Temple_of_Time_Moving_Wall_Dinalfos_Room_Chest = 204,
  Lanayru_Spring_Underwater_Right_Chest = 205,
  Gerudo_Desert_East_Canyon_Chest = 206,
  Forest_Temple_Central_Chest_Behind_Stairs = 207,
  City_in_The_Sky_Baba_Tower_Narrow_Ledge_Chest = 208,
  Outside_South_Castle_Town_Golden_Wolf = 209,
  Snowpeak_Blizzard_Poe = 210,
  Hyrule_Castle_Treasure_Room_Fourth_Chest = 211,
  Arbiters_Grounds_West_Poe = 212,
  Arbiters_Grounds_Torch_Room_East_Chest = 213,
  Temple_of_Time_Big_Key_Chest = 214,
  Lanayru_Spring_Back_Room_Right_Chest = 215,
  City_in_The_Sky_East_Wing_Lower_Level_Chest = 216,
  Lakebed_Temple_West_Second_Floor_Southwest_Underwater_Chest = 217,
  Kakariko_Graveyard_Golden_Wolf = 218,
  Goron_Mines_Beamos_Room_Chest = 219,
  Ashei_Sketch = 220,
  West_Hyrule_Field_Female_Butterfly = 221,
  Sacred_Grove_Female_Snail = 222,
  Faron_Woods_Owl_Statue_Sky_Character = 223,
  Arbiters_Grounds_Spinner_Room_Stalfos_Alcove_Chest = 224,
  Eldin_Stockcave_Lowest_Chest = 225,
  Kakariko_Gorge_Poe = 226,
  Lanayru_Field_Behind_Gate_Underwater_Chest = 227,
  Arbiters_Grounds_East_Lower_Turnable_Redead_Chest = 228,
  Sacred_Grove_Male_Snail = 229,
  Eldin_Field_Stalfos_Grotto_Left_Small_Chest = 230,
  Coro_Bottle = 231,
  Lake_Lantern_Cave_Second_Poe = 232,
  Lake_Lantern_Cave_Fourteenth_Chest = 233,
  Snowpeak_Ruins_Mansion_Map = 234,
  Flight_By_Fowl_Third_Platform_Chest = 235,
  Lake_Lantern_Cave_Twelfth_Chest = 236,
  Snowpeak_Ruins_Dungeon_Reward = 237,
  Gerudo_Desert_Golden_Wolf = 238,
  Gerudo_Desert_Campfire_West_Chest = 239,
  Lakebed_Temple_West_Second_Floor_Northeast_Chest = 240,
  Gerudo_Desert_Female_Dayfly = 241,
  Palace_of_Twilight_West_Wing_Chest_Behind_Wall_of_Darkness = 242,
  Forest_Temple_Big_Baba_Key = 243,
  Sacred_Grove_Master_Sword_Poe = 244,
  Temple_of_Time_First_Staircase_Armos_Chest = 245,
  Outside_South_Castle_Town_Fountain_Chest = 246,
  Arbiters_Grounds_Big_Key_Chest = 247,
  Hyrule_Castle_Treasure_Room_Eighth_Small_Chest = 248,
  Snowpeak_Ruins_West_Courtyard_Buried_Chest = 249,
  Cave_of_Ordeals_Floor_33_Poe = 250,
  Agitha_Male_Dayfly_Reward = 251,
  Palace_of_Twilight_East_Wing_First_Room_Zant_Head_Chest = 252,
  City_in_The_Sky_Big_Key_Chest = 253,
  Hyrule_Castle_Treasure_Room_Third_Small_Chest = 254,
  Goron_Mines_Main_Magnet_Room_Top_Chest = 255,
  Agitha_Male_Butterfly_Reward = 256,
  Outside_South_Castle_Town_Tektite_Grotto_Chest = 257,
  Palace_of_Twilight_West_Wing_Second_Room_Lower_South_Chest = 258,
  Goron_Mines_Gor_Ebizo_Key_Shard = 259,
  Bridge_of_Eldin_Female_Phasmid = 260,
  East_Castle_Town_Bridge_Poe = 261,
  Forest_Temple_Entrance_Vines_Chest = 262,
  Hyrule_Castle_Southeast_Balcony_Tower_Chest = 263,
  Hyrule_Castle_Treasure_Room_Sixth_Small_Chest = 264,
  Faron_Field_Bridge_Chest = 265,
  Death_Mountain_Trail_Poe = 266,
  Snowpeak_Ruins_Lobby_West_Armor_Chest = 267,
  Charlo_Donation_Blessing = 268,
  Snowpeak_Ruins_Lobby_Poe = 269,
  City_in_The_Sky_Aeralfos_Chest = 270,
  Faron_Woods_Owl_Statue_Chest = 271,
  Snowpeak_Ruins_Wooden_Beam_Chandelier_Chest = 272,
  City_in_The_Sky_Argorok_Heart_Container = 273,
  Hyrule_Castle_Graveyard_Grave_Switch_Room_Front_Left_Chest = 274,
  Snowpeak_Ruins_Courtyard_Central_Chest = 275,
  Flight_By_Fowl_Second_Platform_Chest = 276,
  Gerudo_Desert_Male_Dayfly = 277,
  Gerudo_Desert_Northwest_Chest_Behind_Gates = 278,
  Eldin_Spring_Underwater_Chest = 279,
  Kakariko_Gorge_Owl_Statue_Chest = 280,
  City_in_The_Sky_West_Garden_Lone_Island_Chest = 281,
  Hyrule_Castle_Graveyard_Grave_Switch_Room_Right_Chest = 282,
  Lanayru_Spring_West_Double_Clawshot_Chest = 283,
  Snowpeak_Ruins_Broken_Floor_Chest = 284,
  Arbiters_Grounds_Torch_Room_West_Chest = 285,
  Isle_of_Riches_Poe = 286,
  Goron_Mines_Crystal_Switch_Room_Underwater_Chest = 287,
  City_in_The_Sky_West_Wing_First_Chest = 288,
  Snowboard_Racing_Prize = 289,
  Sacred_Grove_Baba_Serpent_Grotto_Chest = 290,
  Lost_Woods_Boulder_Poe = 291,
  City_in_The_Sky_Poe_Above_Central_Fan = 292,
  Ordon_Sword = 293,
  Hyrule_Castle_Treasure_Room_Second_Chest = 294,
  Gerudo_Desert_South_Chest_Behind_Wooden_Gates = 295,
  Snowpeak_Freezard_Grotto_Chest = 296,
  Goron_Mines_Outside_Beamos_Chest = 297,
  Palace_of_Twilight_Zant_Heart_Container = 298,
  Castle_Town_Malo_Mart_Magic_Armor = 299,
  Lakebed_Temple_East_Water_Supply_Clawshot_Chest = 300,
  Jovani_House_Poe = 301,
  Arbiters_Grounds_West_Chandelier_Chest = 302,
  Hyrule_Field_Amphitheater_Owl_Statue_Sky_Character = 303,
  Cave_of_Ordeals_Floor_44_Poe = 304,
  Kakariko_Graveyard_Lantern_Chest = 305,
  Forest_Temple_East_Tile_Worm_Chest = 306,
  Agitha_Female_Snail_Reward = 307,
  Lakebed_Temple_East_Water_Supply_Small_Chest = 308,
  Eldin_Field_Female_Grasshopper = 309,
  Goron_Mines_Dungeon_Reward = 310,
  Arbiters_Grounds_Death_Sword_Chest = 311,
  Lake_Hylia_Bridge_Female_Mantis = 312,
  Arbiters_Grounds_East_Upper_Turnable_Chest = 313,
  City_in_The_Sky_West_Wing_Baba_Balcony_Chest = 314,
  Outside_Arbiters_Grounds_Lantern_Chest = 315,
  Lakebed_Temple_West_Water_Supply_Small_Chest = 316,
  Faron_Mist_Cave_Open_Chest = 317,
  Lakebed_Temple_Lobby_Left_Chest = 318,
  Bulblin_Guard_Key = 319,
  Lake_Hylia_Underwater_Chest = 320,
  Temple_of_Time_Armos_Antechamber_North_Chest = 321,
  Lakebed_Temple_Big_Key_Chest = 322,
  City_in_The_Sky_Chest_Below_Big_Key_Chest = 323,
  Kakariko_Village_Female_Ant = 324,
  Temple_of_Time_Poe_Behind_Gate = 325,
  Kakariko_Gorge_Male_Pill_Bug = 326,
  Palace_of_Twilight_East_Wing_Second_Room_Southeast_Chest = 327,
  Hyrule_Castle_Graveyard_Grave_Switch_Room_Back_Left_Chest = 328,
  City_in_The_Sky_West_Garden_Ledge_Chest = 329,
  Lake_Hylia_Bridge_Male_Mantis = 330,
  Eldin_Stockcave_Upper_Chest = 331,
  Temple_of_Time_Floor_Switch_Puzzle_Room_Upper_Chest = 332,
  Lake_Lantern_Cave_Third_Chest = 333,
  Snowpeak_Ruins_Blizzeta_Heart_Container = 334,
  Lanayru_Field_Spinner_Track_Chest = 335,
  Iza_Raging_Rapids_Minigame = 336,
  Arbiters_Grounds_North_Turning_Room_Chest = 337,
  Agitha_Female_Pill_Bug_Reward = 338,
  Goron_Mines_Main_Magnet_Room_Bottom_Chest = 339,
  Goron_Mines_Gor_Amato_Small_Chest = 340,
  Zoras_Domain_Waterfall_Poe = 341,
  Forest_Temple_Diababa_Heart_Container = 342,
  Arbiters_Grounds_Spinner_Room_Second_Small_Chest = 343,
  Sacred_Grove_Spinner_Chest = 344,
  Arbiters_Grounds_West_Stalfos_West_Chest = 345,
  Forest_Temple_Big_Key_Chest = 346,
  Gerudo_Desert_Rock_Grotto_Second_Poe = 347,
  Lakebed_Temple_East_Second_Floor_Southwest_Chest = 348,
  Temple_of_Time_Armos_Antechamber_East_Chest = 349,
  Temple_of_Time_Armogohma_Heart_Container = 350,
  Snowpeak_Ruins_West_Cannon_Room_Central_Chest = 351,
  Kakariko_Graveyard_Grave_Poe = 352,
  Gerudo_Desert_Campfire_North_Chest = 353,
  Goron_Mines_Fyrus_Heart_Container = 354,
  Hyrule_Castle_Lantern_Staircase_Chest = 355,
  Goron_Mines_Magnet_Maze_Chest = 356,
  Barnes_Bomb_Bag = 357,
  Eldin_Field_Bomskit_Grotto_Lantern_Chest = 358,
  City_in_The_Sky_Central_Outside_Poe_Island_Chest = 359,
  STAR_Prize_2 = 360,
  City_in_The_Sky_West_Garden_Corner_Chest = 361,
  Death_Mountain_Alcove_Chest = 362,
  North_Castle_Town_Golden_Wolf = 363,
  Forest_Temple_Second_Monkey_Under_Bridge_Chest = 364,
  Gerudo_Desert_West_Canyon_Chest = 365,
  Agitha_Male_Mantis_Reward = 366,
  Lanayru_Ice_Block_Puzzle_Cave_Chest = 367,
  City_in_The_Sky_West_Wing_Tile_Worm_Chest = 368,
  Fishing_Hole_Heart_Piece = 369,
  Bridge_of_Eldin_Male_Phasmid = 370,
  Forest_Temple_Windless_Bridge_Chest = 371,
  Zoras_Domain_Light_All_Torches_Chest = 372,
  Palace_of_Twilight_West_Wing_Second_Room_Central_Chest = 373,
  Rutelas_Blessing = 374,
  City_in_The_Sky_East_Wing_After_Dinalfos_Alcove_Chest = 375,
  Snowpeak_Cave_Ice_Poe = 376,
  Lakebed_Temple_Stalactite_Room_Chest = 377,
  Temple_of_Time_Armos_Antechamber_Statue_Chest = 378,
  Cave_of_Ordeals_Floor_17_Poe = 379,
  Arbiters_Grounds_West_Small_Chest_Behind_Block = 380,
  Temple_of_Time_Gilloutine_Chest = 381,
  Cats_Hide_and_Seek_Minigame = 382,
  Goron_Mines_Entrance_Chest = 383,
  Auru_Gift_To_Fyer = 384,
  Snowpeak_Above_Freezard_Grotto_Poe = 385,
  Lake_Lantern_Cave_First_Chest = 386,
  Flight_By_Fowl_Fifth_Platform_Chest = 387,
  Kakariko_Watchtower_Chest = 388,
  Faron_Field_Corner_Grotto_Left_Chest = 389,
  Outside_Lanayru_Spring_Left_Statue_Chest = 390,
  Hidden_Village_Poe = 391,
  Arbiters_Grounds_Ghoul_Rat_Room_Chest = 392,
  Gerudo_Desert_East_Poe = 393,
  Bulblin_Camp_Small_Chest_in_Back_of_Camp = 394,
  Ilia_Memory_Reward = 395,
  Lanayru_Spring_Back_Room_Lantern_Chest = 396,
  Agitha_Female_Ladybug_Reward = 397,
  Palace_of_Twilight_West_Wing_First_Room_Central_Chest = 398,
  City_in_The_Sky_Dungeon_Reward = 399,
  Kakariko_Gorge_Owl_Statue_Sky_Character = 400,
  Forest_Temple_Gale_Boomerang = 401,
  Gerudo_Desert_Skulltula_Grotto_Chest = 402,
  Forest_Temple_West_Deku_Like_Chest = 403,
  Agitha_Male_Stag_Beetle_Reward = 404,
  Faron_Field_Male_Beetle = 405,
  Palace_of_Twilight_East_Wing_First_Room_North_Small_Chest = 406,
  Kakariko_Graveyard_Male_Ant = 407,
  Temple_of_Time_Scales_Upper_Chest = 408,
  Eldin_Field_Stalfos_Grotto_Stalfos_Chest = 409,
  Ordon_Cat_Rescue = 410,
  Lakebed_Temple_Underwater_Maze_Small_Chest = 411,
  Snowpeak_Ruins_West_Cannon_Room_Corner_Chest = 412,
  Lanayru_Spring_Underwater_Left_Chest = 413,
  Lake_Hylia_Bridge_Owl_Statue_Chest = 414,
  Talo_Sharpshooting = 415,
  Lakebed_Temple_Central_Room_Spire_Chest = 416,
  Lake_Hylia_Bridge_Owl_Statue_Sky_Character = 417,
  Gerudo_Desert_North_Small_Chest_Before_Bulblin_Camp = 418,
  Lakebed_Temple_Chandelier_Chest = 419,
  Zoras_Domain_Extinguish_All_Torches_Chest = 420,
  Lake_Lantern_Cave_End_Lantern_Chest = 421,
  Temple_of_Time_Chest_Before_Darknut = 422,
  Snowpeak_Poe_Among_Trees = 423,
  Agitha_Male_Pill_Bug_Reward = 424,
  Herding_Goats_Reward = 425,
  Gerudo_Desert_North_Peahat_Poe = 426,
  Snowpeak_Ruins_Chapel_Chest = 427,
  Lakebed_Temple_Dungeon_Reward = 428,
  Lake_Lantern_Cave_Sixth_Chest = 429,
  Eldin_Field_Bomb_Rock_Chest = 430,
  Agitha_Male_Grasshopper_Reward = 431,
  Flight_By_Fowl_Top_Platform_Reward = 432,
  Kakariko_Gorge_Double_Clawshot_Chest = 433,
  Lanayru_Field_Bridge_Poe = 434,
  Wooden_Statue = 435,
  Fishing_Hole_Bottle = 436,
  Snowpeak_Ruins_East_Courtyard_Chest = 437,
  Lake_Hylia_Alcove_Poe = 438,
  Lanayru_Field_Poe_Grotto_Right_Poe = 439,
  Gerudo_Desert_Owl_Statue_Sky_Character = 440,
  Gerudo_Desert_Owl_Statue_Chest = 441,
  Palace_of_Twilight_Central_First_Room_Chest = 442,
  Snowpeak_Ruins_Wooden_Beam_Central_Chest = 443,
  Snowpeak_Ruins_Ball_and_Chain = 444,
  Plumm_Fruit_Balloon_Minigame = 445,
  Kakariko_Gorge_Spire_Heart_Piece = 446,
  Lakebed_Temple_Before_Deku_Toad_Underwater_Right_Chest = 447,
  Outside_Bulblin_Camp_Poe = 448,
  Doctors_Office_Balcony_Chest = 449,
  Outside_Lanayru_Spring_Right_Statue_Chest = 450,
  Upper_Zoras_River_Poe = 451,
  Bulblin_Camp_Poe = 452,
  Hyrule_Castle_East_Wing_Balcony_Chest = 453,
  Lake_Lantern_Cave_Seventh_Chest = 454,
  Lanayru_Spring_East_Double_Clawshot_Chest = 455,
  Snowpeak_Icy_Summit_Poe = 456,
  Outside_South_Castle_Town_Poe = 457,
  Temple_of_Time_Scales_Gohma_Chest = 458,
  Goron_Mines_Gor_Amato_Key_Shard = 459,
  Kakariko_Gorge_Female_Pill_Bug = 460,
  Eldin_Stockcave_Lantern_Chest = 461,
  Eldin_Lantern_Cave_Lantern_Chest = 462,
  Agitha_Female_Butterfly_Reward = 463,
  Outside_South_Castle_Town_Female_Ladybug = 464,
  Hyrule_Castle_Treasure_Room_First_Chest = 465,
  Telma_Invoice = 466,
  Snowpeak_Ruins_Wooden_Beam_Northwest_Chest = 467,
  Lakebed_Temple_Before_Deku_Toad_Alcove_Chest = 468,
  Eldin_Lantern_Cave_Poe = 469,
  Kakariko_Village_Malo_Mart_Hylian_Shield = 470,
  Palace_of_Twilight_East_Wing_First_Room_East_Alcove = 471,
  Bulblin_Camp_Roasted_Boar = 472,
  Faron_Woods_Golden_Wolf = 473,
  Jovani_60_Poe_Soul_Reward = 474,
}

const checkIdToNameMap: { [key in CheckId]?: string } = {
  [CheckId.Palace_of_Twilight_East_Wing_Second_Room_Southwest_Chest]:
    'Palace of Twilight East Wing Second Room Southwest Chest',
  [CheckId.Faron_Field_Poe]: 'Faron Field Poe',
  [CheckId.Goron_Mines_Crystal_Switch_Room_Small_Chest]:
    'Goron Mines Crystal Switch Room Small Chest',
  [CheckId.Goron_Mines_Gor_Liggs_Key_Shard]: 'Goron Mines Gor Liggs Key Shard',
  [CheckId.Wrestling_With_Bo]: 'Wrestling With Bo',
  [CheckId.Goron_Mines_After_Crystal_Switch_Room_Magnet_Wall_Chest]:
    'Goron Mines After Crystal Switch Room Magnet Wall Chest',
  [CheckId.Agitha_Female_Phasmid_Reward]: 'Agitha Female Phasmid Reward',
  [CheckId.Snowpeak_Ruins_East_Courtyard_Buried_Chest]:
    'Snowpeak Ruins East Courtyard Buried Chest',
  [CheckId.Snowpeak_Ruins_Lobby_East_Armor_Chest]: 'Snowpeak Ruins Lobby East Armor Chest',
  [CheckId.Bridge_of_Eldin_Owl_Statue_Sky_Character]: 'Bridge of Eldin Owl Statue Sky Character',
  [CheckId.Arbiters_Grounds_Entrance_Chest]: 'Arbiters Grounds Entrance Chest',
  [CheckId.Hyrule_Castle_Treasure_Room_Third_Chest]: 'Hyrule Castle Treasure Room Third Chest',
  [CheckId.Arbiters_Grounds_Torch_Room_Poe]: 'Arbiters Grounds Torch Room Poe',
  [CheckId.Palace_of_Twilight_East_Wing_Second_Room_Northwest_Chest]:
    'Palace of Twilight East Wing Second Room Northwest Chest',
  [CheckId.Hyrule_Castle_Graveyard_Owl_Statue_Chest]: 'Hyrule Castle Graveyard Owl Statue Chest',
  [CheckId.Faron_Field_Corner_Grotto_Rear_Chest]: 'Faron Field Corner Grotto Rear Chest',
  [CheckId.Zoras_Domain_Male_Dragonfly]: 'Zoras Domain Male Dragonfly',
  [CheckId.Gerudo_Desert_Lone_Small_Chest]: 'Gerudo Desert Lone Small Chest',
  [CheckId.Gerudo_Desert_Rock_Grotto_Lantern_Chest]: 'Gerudo Desert Rock Grotto Lantern Chest',
  [CheckId.Lake_Hylia_Water_Toadpoli_Grotto_Chest]: 'Lake Hylia Water Toadpoli Grotto Chest',
  [CheckId.Faron_Mist_Stump_Chest]: 'Faron Mist Stump Chest',
  [CheckId.Lanayru_Field_Poe_Grotto_Left_Poe]: 'Lanayru Field Poe Grotto Left Poe',
  [CheckId.City_in_The_Sky_Underwater_West_Chest]: 'City in The Sky Underwater West Chest',
  [CheckId.Temple_of_Time_Dungeon_Reward]: 'Temple of Time Dungeon Reward',
  [CheckId.Ordon_Spring_Golden_Wolf]: 'Ordon Spring Golden Wolf',
  [CheckId.Hyrule_Castle_Main_Hall_Northeast_Chest]: 'Hyrule Castle Main Hall Northeast Chest',
  [CheckId.Gerudo_Desert_Northeast_Chest_Behind_Gates]:
    'Gerudo Desert Northeast Chest Behind Gates',
  [CheckId.Ilia_Charm]: 'Ilia Charm',
  [CheckId.Agitha_Male_Ladybug_Reward]: 'Agitha Male Ladybug Reward',
  [CheckId.Hyrule_Castle_Treasure_Room_Seventh_Small_Chest]:
    'Hyrule Castle Treasure Room Seventh Small Chest',
  [CheckId.Lake_Hylia_Tower_Poe]: 'Lake Hylia Tower Poe',
  [CheckId.Arbiters_Grounds_Spinner_Room_Lower_North_Chest]:
    'Arbiters Grounds Spinner Room Lower North Chest',
  [CheckId.Sacred_Grove_Past_Owl_Statue_Chest]: 'Sacred Grove Past Owl Statue Chest',
  [CheckId.Lakebed_Temple_Morpheel_Heart_Container]: 'Lakebed Temple Morpheel Heart Container',
  [CheckId.Lost_Woods_Lantern_Chest]: 'Lost Woods Lantern Chest',
  [CheckId.Lanayru_Field_Skulltula_Grotto_Chest]: 'Lanayru Field Skulltula Grotto Chest',
  [CheckId.Faron_Mist_Cave_Lantern_Chest]: 'Faron Mist Cave Lantern Chest',
  [CheckId.Eldin_Lantern_Cave_First_Chest]: 'Eldin Lantern Cave First Chest',
  [CheckId.Faron_Field_Corner_Grotto_Right_Chest]: 'Faron Field Corner Grotto Right Chest',
  [CheckId.Ordon_Ranch_Grotto_Lantern_Chest]: 'Ordon Ranch Grotto Lantern Chest',
  [CheckId.Sera_Shop_Slingshot]: 'Sera Shop Slingshot',
  [CheckId.Lakebed_Temple_East_Lower_Waterwheel_Stalactite_Chest]:
    'Lakebed Temple East Lower Waterwheel Stalactite Chest',
  [CheckId.Snowpeak_Ruins_Chest_After_Darkhammer]: 'Snowpeak Ruins Chest After Darkhammer',
  [CheckId.Goron_Mines_Gor_Liggs_Chest]: 'Goron Mines Gor Liggs Chest',
  [CheckId.Arbiters_Grounds_East_Turning_Room_Poe]: 'Arbiters Grounds East Turning Room Poe',
  [CheckId.Lanayru_Field_Female_Stag_Beetle]: 'Lanayru Field Female Stag Beetle',
  [CheckId.Zoras_Domain_Chest_By_Mother_and_Child_Isles]:
    'Zoras Domain Chest By Mother and Child Isles',
  [CheckId.North_Faron_Woods_Deku_Baba_Chest]: 'North Faron Woods Deku Baba Chest',
  [CheckId.City_in_The_Sky_Baba_Tower_Top_Small_Chest]:
    'City in The Sky Baba Tower Top Small Chest',
  [CheckId.Kakariko_Village_Bomb_Rock_Spire_Heart_Piece]:
    'Kakariko Village Bomb Rock Spire Heart Piece',
  [CheckId.Arbiters_Grounds_Stallord_Heart_Container]: 'Arbiters Grounds Stallord Heart Container',
  [CheckId.Zoras_Domain_Chest_Behind_Waterfall]: 'Zoras Domain Chest Behind Waterfall',
  [CheckId.City_in_The_Sky_Central_Outside_Ledge_Chest]:
    'City in The Sky Central Outside Ledge Chest',
  [CheckId.Palace_of_Twilight_East_Wing_First_Room_West_Alcove]:
    'Palace of Twilight East Wing First Room West Alcove',
  [CheckId.Bulblin_Camp_First_Chest_Under_Tower_At_Entrance]:
    'Bulblin Camp First Chest Under Tower At Entrance',
  [CheckId.Arbiters_Grounds_West_Stalfos_Northeast_Chest]:
    'Arbiters Grounds West Stalfos Northeast Chest',
  [CheckId.Outside_South_Castle_Town_Male_Ladybug]: 'Outside South Castle Town Male Ladybug',
  [CheckId.Jovani_20_Poe_Soul_Reward]: 'Jovani 20 Poe Soul Reward',
  [CheckId.West_Hyrule_Field_Helmasaur_Grotto_Chest]: 'West Hyrule Field Helmasaur Grotto Chest',
  [CheckId.Zoras_Domain_Underwater_Goron]: 'Zoras Domain Underwater Goron',
  [CheckId.Kakariko_Inn_Chest]: 'Kakariko Inn Chest',
  [CheckId.Agitha_Female_Beetle_Reward]: 'Agitha Female Beetle Reward',
  [CheckId.Lanayru_Spring_Back_Room_Left_Chest]: 'Lanayru Spring Back Room Left Chest',
  [CheckId.Agitha_Female_Grasshopper_Reward]: 'Agitha Female Grasshopper Reward',
  [CheckId.City_in_The_Sky_Baba_Tower_Alcove_Chest]: 'City in The Sky Baba Tower Alcove Chest',
  [CheckId.Goron_Mines_Gor_Amato_Chest]: 'Goron Mines Gor Amato Chest',
  [CheckId.Goron_Mines_Gor_Ebizo_Chest]: 'Goron Mines Gor Ebizo Chest',
  [CheckId.Faron_Mist_North_Chest]: 'Faron Mist North Chest',
  [CheckId.Lakebed_Temple_West_Lower_Small_Chest]: 'Lakebed Temple West Lower Small Chest',
  [CheckId.Agitha_Male_Phasmid_Reward]: 'Agitha Male Phasmid Reward',
  [CheckId.City_in_The_Sky_Chest_Behind_North_Fan]: 'City in The Sky Chest Behind North Fan',
  [CheckId.Lake_Lantern_Cave_Final_Poe]: 'Lake Lantern Cave Final Poe',
  [CheckId.Temple_of_Time_Lobby_Lantern_Chest]: 'Temple of Time Lobby Lantern Chest',
  [CheckId.Lakebed_Temple_East_Second_Floor_Southeast_Chest]:
    'Lakebed Temple East Second Floor Southeast Chest',
  [CheckId.Hyrule_Field_Amphitheater_Poe]: 'Hyrule Field Amphitheater Poe',
  [CheckId.Gerudo_Desert_Peahat_Ledge_Chest]: 'Gerudo Desert Peahat Ledge Chest',
  [CheckId.Iza_Helping_Hand]: 'Iza Helping Hand',
  [CheckId.Lake_Lantern_Cave_Second_Chest]: 'Lake Lantern Cave Second Chest',
  [CheckId.Lakebed_Temple_Central_Room_Small_Chest]: 'Lakebed Temple Central Room Small Chest',
  [CheckId.Links_Basement_Chest]: 'Links Basement Chest',
  [CheckId.Snowpeak_Cave_Ice_Lantern_Chest]: 'Snowpeak Cave Ice Lantern Chest',
  [CheckId.Gerudo_Desert_Poe_Above_Cave_of_Ordeals]: 'Gerudo Desert Poe Above Cave of Ordeals',
  [CheckId.Eldin_Field_Water_Bomb_Fish_Grotto_Chest]: 'Eldin Field Water Bomb Fish Grotto Chest',
  [CheckId.Kakariko_Village_Watchtower_Poe]: 'Kakariko Village Watchtower Poe',
  [CheckId.Agitha_Female_Dragonfly_Reward]: 'Agitha Female Dragonfly Reward',
  [CheckId.Gift_From_Ralis]: 'Gift From Ralis',
  [CheckId.South_Faron_Cave_Chest]: 'South Faron Cave Chest',
  [CheckId.Lakebed_Temple_West_Second_Floor_Southeast_Chest]:
    'Lakebed Temple West Second Floor Southeast Chest',
  [CheckId.Temple_of_Time_Darknut_Chest]: 'Temple of Time Darknut Chest',
  [CheckId.Forest_Temple_Central_North_Chest]: 'Forest Temple Central North Chest',
  [CheckId.Lanayru_Field_Male_Stag_Beetle]: 'Lanayru Field Male Stag Beetle',
  [CheckId.City_in_The_Sky_Underwater_East_Chest]: 'City in The Sky Underwater East Chest',
  [CheckId.Forest_Temple_East_Water_Cave_Chest]: 'Forest Temple East Water Cave Chest',
  [CheckId.Hyrule_Castle_Treasure_Room_Second_Small_Chest]:
    'Hyrule Castle Treasure Room Second Small Chest',
  [CheckId.Lake_Hylia_Bridge_Vines_Chest]: 'Lake Hylia Bridge Vines Chest',
  [CheckId.City_in_The_Sky_East_Wing_After_Dinalfos_Ledge_Chest]:
    'City in The Sky East Wing After Dinalfos Ledge Chest',
  [CheckId.Snowpeak_Ruins_Lobby_Armor_Poe]: 'Snowpeak Ruins Lobby Armor Poe',
  [CheckId.Faron_Field_Tree_Heart_Piece]: 'Faron Field Tree Heart Piece',
  [CheckId.Eldin_Field_Stalfos_Grotto_Right_Small_Chest]:
    'Eldin Field Stalfos Grotto Right Small Chest',
  [CheckId.Lake_Lantern_Cave_First_Poe]: 'Lake Lantern Cave First Poe',
  [CheckId.Hyrule_Castle_Treasure_Room_Fourth_Small_Chest]:
    'Hyrule Castle Treasure Room Fourth Small Chest',
  [CheckId.Kakariko_Village_Malo_Mart_Hawkeye]: 'Kakariko Village Malo Mart Hawkeye',
  [CheckId.Uli_Cradle_Delivery]: 'Uli Cradle Delivery',
  [CheckId.Flight_By_Fowl_Ledge_Poe]: 'Flight By Fowl Ledge Poe',
  [CheckId.Lakebed_Temple_West_Water_Supply_Chest]: 'Lakebed Temple West Water Supply Chest',
  [CheckId.Palace_of_Twilight_East_Wing_Second_Room_Northeast_Chest]:
    'Palace of Twilight East Wing Second Room Northeast Chest',
  [CheckId.Kakariko_Village_Bomb_Shop_Poe]: 'Kakariko Village Bomb Shop Poe',
  [CheckId.Faron_Mist_Poe]: 'Faron Mist Poe',
  [CheckId.Lake_Hylia_Bridge_Cliff_Poe]: 'Lake Hylia Bridge Cliff Poe',
  [CheckId.Hyrule_Castle_Main_Hall_Southwest_Chest]: 'Hyrule Castle Main Hall Southwest Chest',
  [CheckId.Wooden_Sword_Chest]: 'Wooden Sword Chest',
  [CheckId.Goron_Mines_Dangoro_Chest]: 'Goron Mines Dangoro Chest',
  [CheckId.City_in_The_Sky_Garden_Island_Poe]: 'City in The Sky Garden Island Poe',
  [CheckId.Faron_Field_Female_Beetle]: 'Faron Field Female Beetle',
  [CheckId.Eldin_Field_Male_Grasshopper]: 'Eldin Field Male Grasshopper',
  [CheckId.Gerudo_Desert_Rock_Grotto_First_Poe]: 'Gerudo Desert Rock Grotto First Poe',
  [CheckId.Eldin_Lantern_Cave_Second_Chest]: 'Eldin Lantern Cave Second Chest',
  [CheckId.Palace_of_Twilight_West_Wing_Second_Room_Southeast_Chest]:
    'Palace of Twilight West Wing Second Room Southeast Chest',
  [CheckId.Arbiters_Grounds_East_Upper_Turnable_Redead_Chest]:
    'Arbiters Grounds East Upper Turnable Redead Chest',
  [CheckId.Sacred_Grove_Temple_of_Time_Owl_Statue_Poe]:
    'Sacred Grove Temple of Time Owl Statue Poe',
  [CheckId.Forest_Temple_West_Tile_Worm_Room_Vines_Chest]:
    'Forest Temple West Tile Worm Room Vines Chest',
  [CheckId.Agitha_Male_Dragonfly_Reward]: 'Agitha Male Dragonfly Reward',
  [CheckId.City_in_The_Sky_East_Tile_Worm_Small_Chest]:
    'City in The Sky East Tile Worm Small Chest',
  [CheckId.Palace_of_Twilight_Central_Tower_Chest]: 'Palace of Twilight Central Tower Chest',
  [CheckId.Outside_Arbiters_Grounds_Poe]: 'Outside Arbiters Grounds Poe',
  [CheckId.Outside_South_Castle_Town_Double_Clawshot_Chasm_Chest]:
    'Outside South Castle Town Double Clawshot Chasm Chest',
  [CheckId.Hyrule_Field_Amphitheater_Owl_Statue_Chest]:
    'Hyrule Field Amphitheater Owl Statue Chest',
  [CheckId.Snowpeak_Ruins_Northeast_Chandelier_Chest]: 'Snowpeak Ruins Northeast Chandelier Chest',
  [CheckId.Hyrule_Castle_West_Courtyard_North_Small_Chest]:
    'Hyrule Castle West Courtyard North Small Chest',
  [CheckId.Agitha_Female_Stag_Beetle_Reward]: 'Agitha Female Stag Beetle Reward',
  [CheckId.Lakebed_Temple_West_Second_Floor_Central_Small_Chest]:
    'Lakebed Temple West Second Floor Central Small Chest',
  [CheckId.Agitha_Female_Mantis_Reward]: 'Agitha Female Mantis Reward',
  [CheckId.Lakebed_Temple_Lobby_Rear_Chest]: 'Lakebed Temple Lobby Rear Chest',
  [CheckId.Bridge_of_Eldin_Owl_Statue_Chest]: 'Bridge of Eldin Owl Statue Chest',
  [CheckId.West_Hyrule_Field_Golden_Wolf]: 'West Hyrule Field Golden Wolf',
  [CheckId.Lake_Hylia_Bridge_Cliff_Chest]: 'Lake Hylia Bridge Cliff Chest',
  [CheckId.City_in_The_Sky_West_Garden_Lower_Chest]: 'City in The Sky West Garden Lower Chest',
  [CheckId.Goron_Mines_Outside_Clawshot_Chest]: 'Goron Mines Outside Clawshot Chest',
  [CheckId.Lake_Lantern_Cave_Fifth_Chest]: 'Lake Lantern Cave Fifth Chest',
  [CheckId.Palace_of_Twilight_Big_Key_Chest]: 'Palace of Twilight Big Key Chest',
  [CheckId.Agitha_Male_Beetle_Reward]: 'Agitha Male Beetle Reward',
  [CheckId.Gerudo_Desert_Campfire_East_Chest]: 'Gerudo Desert Campfire East Chest',
  [CheckId.Hyrule_Castle_Big_Key_Chest]: 'Hyrule Castle Big Key Chest',
  [CheckId.Temple_of_Time_Moving_Wall_Beamos_Room_Chest]:
    'Temple of Time Moving Wall Beamos Room Chest',
  [CheckId.Lake_Lantern_Cave_Fourth_Chest]: 'Lake Lantern Cave Fourth Chest',
  [CheckId.Lakebed_Temple_East_Lower_Waterwheel_Bridge_Chest]:
    'Lakebed Temple East Lower Waterwheel Bridge Chest',
  [CheckId.City_in_The_Sky_East_First_Wing_Chest_After_Fans]:
    'City in The Sky East First Wing Chest After Fans',
  [CheckId.Lake_Lantern_Cave_Tenth_Chest]: 'Lake Lantern Cave Tenth Chest',
  [CheckId.Lake_Lantern_Cave_Ninth_Chest]: 'Lake Lantern Cave Ninth Chest',
  [CheckId.Kakariko_Watchtower_Alcove_Chest]: 'Kakariko Watchtower Alcove Chest',
  [CheckId.West_Hyrule_Field_Male_Butterfly]: 'West Hyrule Field Male Butterfly',
  [CheckId.Hyrule_Castle_King_Bulblin_Key]: 'Hyrule Castle King Bulblin Key',
  [CheckId.Hyrule_Castle_East_Wing_Boomerang_Puzzle_Chest]:
    'Hyrule Castle East Wing Boomerang Puzzle Chest',
  [CheckId.Palace_of_Twilight_Central_Outdoor_Chest]: 'Palace of Twilight Central Outdoor Chest',
  [CheckId.Hyrule_Castle_Treasure_Room_First_Small_Chest]:
    'Hyrule Castle Treasure Room First Small Chest',
  [CheckId.Goron_Mines_Outside_Underwater_Chest]: 'Goron Mines Outside Underwater Chest',
  [CheckId.Lake_Lantern_Cave_Eleventh_Chest]: 'Lake Lantern Cave Eleventh Chest',
  [CheckId.Agitha_Female_Ant_Reward]: 'Agitha Female Ant Reward',
  [CheckId.Cave_of_Ordeals_Great_Fairy_Reward]: 'Cave of Ordeals Great Fairy Reward',
  [CheckId.Forest_Temple_Central_Chest_Hanging_From_Web]:
    'Forest Temple Central Chest Hanging From Web',
  [CheckId.Lost_Woods_Waterfall_Poe]: 'Lost Woods Waterfall Poe',
  [CheckId.Kakariko_Graveyard_Open_Poe]: 'Kakariko Graveyard Open Poe',
  [CheckId.Eldin_Field_Bomskit_Grotto_Left_Chest]: 'Eldin Field Bomskit Grotto Left Chest',
  [CheckId.Hyrule_Castle_West_Courtyard_Central_Small_Chest]:
    'Hyrule Castle West Courtyard Central Small Chest',
  [CheckId.City_in_The_Sky_West_Wing_Narrow_Ledge_Chest]:
    'City in The Sky West Wing Narrow Ledge Chest',
  [CheckId.Snowpeak_Ruins_Ordon_Pumpkin_Chest]: 'Snowpeak Ruins Ordon Pumpkin Chest',
  [CheckId.Skybook_From_Impaz]: 'Skybook From Impaz',
  [CheckId.STAR_Prize_1]: 'STAR Prize 1',
  [CheckId.Hyrule_Castle_Treasure_Room_Fifth_Chest]: 'Hyrule Castle Treasure Room Fifth Chest',
  [CheckId.Zoras_Domain_Mother_and_Child_Isle_Poe]: 'Zoras Domain Mother and Child Isle Poe',
  [CheckId.Ordon_Shield]: 'Ordon Shield',
  [CheckId.Flight_By_Fowl_Fourth_Platform_Chest]: 'Flight By Fowl Fourth Platform Chest',
  [CheckId.Goron_Springwater_Rush]: 'Goron Springwater Rush',
  [CheckId.Arbiters_Grounds_Hidden_Wall_Poe]: 'Arbiters Grounds Hidden Wall Poe',
  [CheckId.Agitha_Female_Dayfly_Reward]: 'Agitha Female Dayfly Reward',
  [CheckId.Outside_South_Castle_Town_Tightrope_Chest]: 'Outside South Castle Town Tightrope Chest',
  [CheckId.Lake_Hylia_Bridge_Bubble_Grotto_Chest]: 'Lake Hylia Bridge Bubble Grotto Chest',
  [CheckId.Hyrule_Castle_Main_Hall_Northwest_Chest]: 'Hyrule Castle Main Hall Northwest Chest',
  [CheckId.Snowpeak_Ruins_Ice_Room_Poe]: 'Snowpeak Ruins Ice Room Poe',
  [CheckId.Forest_Temple_Dungeon_Reward]: 'Forest Temple Dungeon Reward',
  [CheckId.Arbiters_Grounds_Spinner_Room_Lower_Central_Small_Chest]:
    'Arbiters Grounds Spinner Room Lower Central Small Chest',
  [CheckId.Hyrule_Castle_Treasure_Room_Fifth_Small_Chest]:
    'Hyrule Castle Treasure Room Fifth Small Chest',
  [CheckId.Goron_Mines_Chest_Before_Dangoro]: 'Goron Mines Chest Before Dangoro',
  [CheckId.Agitha_Male_Snail_Reward]: 'Agitha Male Snail Reward',
  [CheckId.Agitha_Male_Ant_Reward]: 'Agitha Male Ant Reward',
  [CheckId.Lakebed_Temple_Before_Deku_Toad_Underwater_Left_Chest]:
    'Lakebed Temple Before Deku Toad Underwater Left Chest',
  [CheckId.Temple_of_Time_Poe_Above_Scales]: 'Temple of Time Poe Above Scales',
  [CheckId.Forest_Temple_North_Deku_Like_Chest]: 'Forest Temple North Deku Like Chest',
  [CheckId.Lakebed_Temple_Central_Room_Chest]: 'Lakebed Temple Central Room Chest',
  [CheckId.Temple_of_Time_First_Staircase_Gohma_Gate_Chest]:
    'Temple of Time First Staircase Gohma Gate Chest',
  [CheckId.Temple_of_Time_First_Staircase_Window_Chest]:
    'Temple of Time First Staircase Window Chest',
  [CheckId.Forest_Temple_Totem_Pole_Chest]: 'Forest Temple Totem Pole Chest',
  [CheckId.Faron_Mist_South_Chest]: 'Faron Mist South Chest',
  [CheckId.Lake_Lantern_Cave_Eighth_Chest]: 'Lake Lantern Cave Eighth Chest',
  [CheckId.Snowpeak_Ruins_Lobby_Chandelier_Chest]: 'Snowpeak Ruins Lobby Chandelier Chest',
  [CheckId.Lakebed_Temple_Deku_Toad_Chest]: 'Lakebed Temple Deku Toad Chest',
  [CheckId.Lake_Hylia_Dock_Poe]: 'Lake Hylia Dock Poe',
  [CheckId.Lake_Hylia_Shell_Blade_Grotto_Chest]: 'Lake Hylia Shell Blade Grotto Chest',
  [CheckId.Forest_Temple_West_Tile_Worm_Chest_Behind_Stairs]:
    'Forest Temple West Tile Worm Chest Behind Stairs',
  [CheckId.Renados_Letter]: 'Renados Letter',
  [CheckId.Lake_Lantern_Cave_Thirteenth_Chest]: 'Lake Lantern Cave Thirteenth Chest',
  [CheckId.Arbiters_Grounds_Spinner_Room_First_Small_Chest]:
    'Arbiters Grounds Spinner Room First Small Chest',
  [CheckId.Palace_of_Twilight_Collect_Both_Sols]: 'Palace of Twilight Collect Both Sols',
  [CheckId.Upper_Zoras_River_Female_Dragonfly]: 'Upper Zoras River Female Dragonfly',
  [CheckId.Temple_of_Time_Moving_Wall_Dinalfos_Room_Chest]:
    'Temple of Time Moving Wall Dinalfos Room Chest',
  [CheckId.Lanayru_Spring_Underwater_Right_Chest]: 'Lanayru Spring Underwater Right Chest',
  [CheckId.Gerudo_Desert_East_Canyon_Chest]: 'Gerudo Desert East Canyon Chest',
  [CheckId.Forest_Temple_Central_Chest_Behind_Stairs]: 'Forest Temple Central Chest Behind Stairs',
  [CheckId.City_in_The_Sky_Baba_Tower_Narrow_Ledge_Chest]:
    'City in The Sky Baba Tower Narrow Ledge Chest',
  [CheckId.Outside_South_Castle_Town_Golden_Wolf]: 'Outside South Castle Town Golden Wolf',
  [CheckId.Snowpeak_Blizzard_Poe]: 'Snowpeak Blizzard Poe',
  [CheckId.Hyrule_Castle_Treasure_Room_Fourth_Chest]: 'Hyrule Castle Treasure Room Fourth Chest',
  [CheckId.Arbiters_Grounds_West_Poe]: 'Arbiters Grounds West Poe',
  [CheckId.Arbiters_Grounds_Torch_Room_East_Chest]: 'Arbiters Grounds Torch Room East Chest',
  [CheckId.Temple_of_Time_Big_Key_Chest]: 'Temple of Time Big Key Chest',
  [CheckId.Lanayru_Spring_Back_Room_Right_Chest]: 'Lanayru Spring Back Room Right Chest',
  [CheckId.City_in_The_Sky_East_Wing_Lower_Level_Chest]:
    'City in The Sky East Wing Lower Level Chest',
  [CheckId.Lakebed_Temple_West_Second_Floor_Southwest_Underwater_Chest]:
    'Lakebed Temple West Second Floor Southwest Underwater Chest',
  [CheckId.Kakariko_Graveyard_Golden_Wolf]: 'Kakariko Graveyard Golden Wolf',
  [CheckId.Goron_Mines_Beamos_Room_Chest]: 'Goron Mines Beamos Room Chest',
  [CheckId.Ashei_Sketch]: 'Ashei Sketch',
  [CheckId.West_Hyrule_Field_Female_Butterfly]: 'West Hyrule Field Female Butterfly',
  [CheckId.Sacred_Grove_Female_Snail]: 'Sacred Grove Female Snail',
  [CheckId.Faron_Woods_Owl_Statue_Sky_Character]: 'Faron Woods Owl Statue Sky Character',
  [CheckId.Arbiters_Grounds_Spinner_Room_Stalfos_Alcove_Chest]:
    'Arbiters Grounds Spinner Room Stalfos Alcove Chest',
  [CheckId.Eldin_Stockcave_Lowest_Chest]: 'Eldin Stockcave Lowest Chest',
  [CheckId.Kakariko_Gorge_Poe]: 'Kakariko Gorge Poe',
  [CheckId.Lanayru_Field_Behind_Gate_Underwater_Chest]:
    'Lanayru Field Behind Gate Underwater Chest',
  [CheckId.Arbiters_Grounds_East_Lower_Turnable_Redead_Chest]:
    'Arbiters Grounds East Lower Turnable Redead Chest',
  [CheckId.Sacred_Grove_Male_Snail]: 'Sacred Grove Male Snail',
  [CheckId.Eldin_Field_Stalfos_Grotto_Left_Small_Chest]:
    'Eldin Field Stalfos Grotto Left Small Chest',
  [CheckId.Coro_Bottle]: 'Coro Bottle',
  [CheckId.Lake_Lantern_Cave_Second_Poe]: 'Lake Lantern Cave Second Poe',
  [CheckId.Lake_Lantern_Cave_Fourteenth_Chest]: 'Lake Lantern Cave Fourteenth Chest',
  [CheckId.Snowpeak_Ruins_Mansion_Map]: 'Snowpeak Ruins Mansion Map',
  [CheckId.Flight_By_Fowl_Third_Platform_Chest]: 'Flight By Fowl Third Platform Chest',
  [CheckId.Lake_Lantern_Cave_Twelfth_Chest]: 'Lake Lantern Cave Twelfth Chest',
  [CheckId.Snowpeak_Ruins_Dungeon_Reward]: 'Snowpeak Ruins Dungeon Reward',
  [CheckId.Gerudo_Desert_Golden_Wolf]: 'Gerudo Desert Golden Wolf',
  [CheckId.Gerudo_Desert_Campfire_West_Chest]: 'Gerudo Desert Campfire West Chest',
  [CheckId.Lakebed_Temple_West_Second_Floor_Northeast_Chest]:
    'Lakebed Temple West Second Floor Northeast Chest',
  [CheckId.Gerudo_Desert_Female_Dayfly]: 'Gerudo Desert Female Dayfly',
  [CheckId.Palace_of_Twilight_West_Wing_Chest_Behind_Wall_of_Darkness]:
    'Palace of Twilight West Wing Chest Behind Wall of Darkness',
  [CheckId.Forest_Temple_Big_Baba_Key]: 'Forest Temple Big Baba Key',
  [CheckId.Sacred_Grove_Master_Sword_Poe]: 'Sacred Grove Master Sword Poe',
  [CheckId.Temple_of_Time_First_Staircase_Armos_Chest]:
    'Temple of Time First Staircase Armos Chest',
  [CheckId.Outside_South_Castle_Town_Fountain_Chest]: 'Outside South Castle Town Fountain Chest',
  [CheckId.Arbiters_Grounds_Big_Key_Chest]: 'Arbiters Grounds Big Key Chest',
  [CheckId.Hyrule_Castle_Treasure_Room_Eighth_Small_Chest]:
    'Hyrule Castle Treasure Room Eighth Small Chest',
  [CheckId.Snowpeak_Ruins_West_Courtyard_Buried_Chest]:
    'Snowpeak Ruins West Courtyard Buried Chest',
  [CheckId.Cave_of_Ordeals_Floor_33_Poe]: 'Cave of Ordeals Floor 33 Poe',
  [CheckId.Agitha_Male_Dayfly_Reward]: 'Agitha Male Dayfly Reward',
  [CheckId.Palace_of_Twilight_East_Wing_First_Room_Zant_Head_Chest]:
    'Palace of Twilight East Wing First Room Zant Head Chest',
  [CheckId.City_in_The_Sky_Big_Key_Chest]: 'City in The Sky Big Key Chest',
  [CheckId.Hyrule_Castle_Treasure_Room_Third_Small_Chest]:
    'Hyrule Castle Treasure Room Third Small Chest',
  [CheckId.Goron_Mines_Main_Magnet_Room_Top_Chest]: 'Goron Mines Main Magnet Room Top Chest',
  [CheckId.Agitha_Male_Butterfly_Reward]: 'Agitha Male Butterfly Reward',
  [CheckId.Outside_South_Castle_Town_Tektite_Grotto_Chest]:
    'Outside South Castle Town Tektite Grotto Chest',
  [CheckId.Palace_of_Twilight_West_Wing_Second_Room_Lower_South_Chest]:
    'Palace of Twilight West Wing Second Room Lower South Chest',
  [CheckId.Goron_Mines_Gor_Ebizo_Key_Shard]: 'Goron Mines Gor Ebizo Key Shard',
  [CheckId.Bridge_of_Eldin_Female_Phasmid]: 'Bridge of Eldin Female Phasmid',
  [CheckId.East_Castle_Town_Bridge_Poe]: 'East Castle Town Bridge Poe',
  [CheckId.Forest_Temple_Entrance_Vines_Chest]: 'Forest Temple Entrance Vines Chest',
  [CheckId.Hyrule_Castle_Southeast_Balcony_Tower_Chest]:
    'Hyrule Castle Southeast Balcony Tower Chest',
  [CheckId.Hyrule_Castle_Treasure_Room_Sixth_Small_Chest]:
    'Hyrule Castle Treasure Room Sixth Small Chest',
  [CheckId.Faron_Field_Bridge_Chest]: 'Faron Field Bridge Chest',
  [CheckId.Death_Mountain_Trail_Poe]: 'Death Mountain Trail Poe',
  [CheckId.Snowpeak_Ruins_Lobby_West_Armor_Chest]: 'Snowpeak Ruins Lobby West Armor Chest',
  [CheckId.Charlo_Donation_Blessing]: 'Charlo Donation Blessing',
  [CheckId.Snowpeak_Ruins_Lobby_Poe]: 'Snowpeak Ruins Lobby Poe',
  [CheckId.City_in_The_Sky_Aeralfos_Chest]: 'City in The Sky Aeralfos Chest',
  [CheckId.Faron_Woods_Owl_Statue_Chest]: 'Faron Woods Owl Statue Chest',
  [CheckId.Snowpeak_Ruins_Wooden_Beam_Chandelier_Chest]:
    'Snowpeak Ruins Wooden Beam Chandelier Chest',
  [CheckId.City_in_The_Sky_Argorok_Heart_Container]: 'City in The Sky Argorok Heart Container',
  [CheckId.Hyrule_Castle_Graveyard_Grave_Switch_Room_Front_Left_Chest]:
    'Hyrule Castle Graveyard Grave Switch Room Front Left Chest',
  [CheckId.Snowpeak_Ruins_Courtyard_Central_Chest]: 'Snowpeak Ruins Courtyard Central Chest',
  [CheckId.Flight_By_Fowl_Second_Platform_Chest]: 'Flight By Fowl Second Platform Chest',
  [CheckId.Gerudo_Desert_Male_Dayfly]: 'Gerudo Desert Male Dayfly',
  [CheckId.Gerudo_Desert_Northwest_Chest_Behind_Gates]:
    'Gerudo Desert Northwest Chest Behind Gates',
  [CheckId.Eldin_Spring_Underwater_Chest]: 'Eldin Spring Underwater Chest',
  [CheckId.Kakariko_Gorge_Owl_Statue_Chest]: 'Kakariko Gorge Owl Statue Chest',
  [CheckId.City_in_The_Sky_West_Garden_Lone_Island_Chest]:
    'City in The Sky West Garden Lone Island Chest',
  [CheckId.Hyrule_Castle_Graveyard_Grave_Switch_Room_Right_Chest]:
    'Hyrule Castle Graveyard Grave Switch Room Right Chest',
  [CheckId.Lanayru_Spring_West_Double_Clawshot_Chest]: 'Lanayru Spring West Double Clawshot Chest',
  [CheckId.Snowpeak_Ruins_Broken_Floor_Chest]: 'Snowpeak Ruins Broken Floor Chest',
  [CheckId.Arbiters_Grounds_Torch_Room_West_Chest]: 'Arbiters Grounds Torch Room West Chest',
  [CheckId.Isle_of_Riches_Poe]: 'Isle of Riches Poe',
  [CheckId.Goron_Mines_Crystal_Switch_Room_Underwater_Chest]:
    'Goron Mines Crystal Switch Room Underwater Chest',
  [CheckId.City_in_The_Sky_West_Wing_First_Chest]: 'City in The Sky West Wing First Chest',
  [CheckId.Snowboard_Racing_Prize]: 'Snowboard Racing Prize',
  [CheckId.Sacred_Grove_Baba_Serpent_Grotto_Chest]: 'Sacred Grove Baba Serpent Grotto Chest',
  [CheckId.Lost_Woods_Boulder_Poe]: 'Lost Woods Boulder Poe',
  [CheckId.City_in_The_Sky_Poe_Above_Central_Fan]: 'City in The Sky Poe Above Central Fan',
  [CheckId.Ordon_Sword]: 'Ordon Sword',
  [CheckId.Hyrule_Castle_Treasure_Room_Second_Chest]: 'Hyrule Castle Treasure Room Second Chest',
  [CheckId.Gerudo_Desert_South_Chest_Behind_Wooden_Gates]:
    'Gerudo Desert South Chest Behind Wooden Gates',
  [CheckId.Snowpeak_Freezard_Grotto_Chest]: 'Snowpeak Freezard Grotto Chest',
  [CheckId.Goron_Mines_Outside_Beamos_Chest]: 'Goron Mines Outside Beamos Chest',
  [CheckId.Palace_of_Twilight_Zant_Heart_Container]: 'Palace of Twilight Zant Heart Container',
  [CheckId.Castle_Town_Malo_Mart_Magic_Armor]: 'Castle Town Malo Mart Magic Armor',
  [CheckId.Lakebed_Temple_East_Water_Supply_Clawshot_Chest]:
    'Lakebed Temple East Water Supply Clawshot Chest',
  [CheckId.Jovani_House_Poe]: 'Jovani House Poe',
  [CheckId.Arbiters_Grounds_West_Chandelier_Chest]: 'Arbiters Grounds West Chandelier Chest',
  [CheckId.Hyrule_Field_Amphitheater_Owl_Statue_Sky_Character]:
    'Hyrule Field Amphitheater Owl Statue Sky Character',
  [CheckId.Cave_of_Ordeals_Floor_44_Poe]: 'Cave of Ordeals Floor 44 Poe',
  [CheckId.Kakariko_Graveyard_Lantern_Chest]: 'Kakariko Graveyard Lantern Chest',
  [CheckId.Forest_Temple_East_Tile_Worm_Chest]: 'Forest Temple East Tile Worm Chest',
  [CheckId.Agitha_Female_Snail_Reward]: 'Agitha Female Snail Reward',
  [CheckId.Lakebed_Temple_East_Water_Supply_Small_Chest]:
    'Lakebed Temple East Water Supply Small Chest',
  [CheckId.Eldin_Field_Female_Grasshopper]: 'Eldin Field Female Grasshopper',
  [CheckId.Goron_Mines_Dungeon_Reward]: 'Goron Mines Dungeon Reward',
  [CheckId.Arbiters_Grounds_Death_Sword_Chest]: 'Arbiters Grounds Death Sword Chest',
  [CheckId.Lake_Hylia_Bridge_Female_Mantis]: 'Lake Hylia Bridge Female Mantis',
  [CheckId.Arbiters_Grounds_East_Upper_Turnable_Chest]:
    'Arbiters Grounds East Upper Turnable Chest',
  [CheckId.City_in_The_Sky_West_Wing_Baba_Balcony_Chest]:
    'City in The Sky West Wing Baba Balcony Chest',
  [CheckId.Outside_Arbiters_Grounds_Lantern_Chest]: 'Outside Arbiters Grounds Lantern Chest',
  [CheckId.Lakebed_Temple_West_Water_Supply_Small_Chest]:
    'Lakebed Temple West Water Supply Small Chest',
  [CheckId.Faron_Mist_Cave_Open_Chest]: 'Faron Mist Cave Open Chest',
  [CheckId.Lakebed_Temple_Lobby_Left_Chest]: 'Lakebed Temple Lobby Left Chest',
  [CheckId.Bulblin_Guard_Key]: 'Bulblin Guard Key',
  [CheckId.Lake_Hylia_Underwater_Chest]: 'Lake Hylia Underwater Chest',
  [CheckId.Temple_of_Time_Armos_Antechamber_North_Chest]:
    'Temple of Time Armos Antechamber North Chest',
  [CheckId.Lakebed_Temple_Big_Key_Chest]: 'Lakebed Temple Big Key Chest',
  [CheckId.City_in_The_Sky_Chest_Below_Big_Key_Chest]: 'City in The Sky Chest Below Big Key Chest',
  [CheckId.Kakariko_Village_Female_Ant]: 'Kakariko Village Female Ant',
  [CheckId.Temple_of_Time_Poe_Behind_Gate]: 'Temple of Time Poe Behind Gate',
  [CheckId.Kakariko_Gorge_Male_Pill_Bug]: 'Kakariko Gorge Male Pill Bug',
  [CheckId.Palace_of_Twilight_East_Wing_Second_Room_Southeast_Chest]:
    'Palace of Twilight East Wing Second Room Southeast Chest',
  [CheckId.Hyrule_Castle_Graveyard_Grave_Switch_Room_Back_Left_Chest]:
    'Hyrule Castle Graveyard Grave Switch Room Back Left Chest',
  [CheckId.City_in_The_Sky_West_Garden_Ledge_Chest]: 'City in The Sky West Garden Ledge Chest',
  [CheckId.Lake_Hylia_Bridge_Male_Mantis]: 'Lake Hylia Bridge Male Mantis',
  [CheckId.Eldin_Stockcave_Upper_Chest]: 'Eldin Stockcave Upper Chest',
  [CheckId.Temple_of_Time_Floor_Switch_Puzzle_Room_Upper_Chest]:
    'Temple of Time Floor Switch Puzzle Room Upper Chest',
  [CheckId.Lake_Lantern_Cave_Third_Chest]: 'Lake Lantern Cave Third Chest',
  [CheckId.Snowpeak_Ruins_Blizzeta_Heart_Container]: 'Snowpeak Ruins Blizzeta Heart Container',
  [CheckId.Lanayru_Field_Spinner_Track_Chest]: 'Lanayru Field Spinner Track Chest',
  [CheckId.Iza_Raging_Rapids_Minigame]: 'Iza Raging Rapids Minigame',
  [CheckId.Arbiters_Grounds_North_Turning_Room_Chest]: 'Arbiters Grounds North Turning Room Chest',
  [CheckId.Agitha_Female_Pill_Bug_Reward]: 'Agitha Female Pill Bug Reward',
  [CheckId.Goron_Mines_Main_Magnet_Room_Bottom_Chest]: 'Goron Mines Main Magnet Room Bottom Chest',
  [CheckId.Goron_Mines_Gor_Amato_Small_Chest]: 'Goron Mines Gor Amato Small Chest',
  [CheckId.Zoras_Domain_Waterfall_Poe]: 'Zoras Domain Waterfall Poe',
  [CheckId.Forest_Temple_Diababa_Heart_Container]: 'Forest Temple Diababa Heart Container',
  [CheckId.Arbiters_Grounds_Spinner_Room_Second_Small_Chest]:
    'Arbiters Grounds Spinner Room Second Small Chest',
  [CheckId.Sacred_Grove_Spinner_Chest]: 'Sacred Grove Spinner Chest',
  [CheckId.Arbiters_Grounds_West_Stalfos_West_Chest]: 'Arbiters Grounds West Stalfos West Chest',
  [CheckId.Forest_Temple_Big_Key_Chest]: 'Forest Temple Big Key Chest',
  [CheckId.Gerudo_Desert_Rock_Grotto_Second_Poe]: 'Gerudo Desert Rock Grotto Second Poe',
  [CheckId.Lakebed_Temple_East_Second_Floor_Southwest_Chest]:
    'Lakebed Temple East Second Floor Southwest Chest',
  [CheckId.Temple_of_Time_Armos_Antechamber_East_Chest]:
    'Temple of Time Armos Antechamber East Chest',
  [CheckId.Temple_of_Time_Armogohma_Heart_Container]: 'Temple of Time Armogohma Heart Container',
  [CheckId.Snowpeak_Ruins_West_Cannon_Room_Central_Chest]:
    'Snowpeak Ruins West Cannon Room Central Chest',
  [CheckId.Kakariko_Graveyard_Grave_Poe]: 'Kakariko Graveyard Grave Poe',
  [CheckId.Gerudo_Desert_Campfire_North_Chest]: 'Gerudo Desert Campfire North Chest',
  [CheckId.Goron_Mines_Fyrus_Heart_Container]: 'Goron Mines Fyrus Heart Container',
  [CheckId.Hyrule_Castle_Lantern_Staircase_Chest]: 'Hyrule Castle Lantern Staircase Chest',
  [CheckId.Goron_Mines_Magnet_Maze_Chest]: 'Goron Mines Magnet Maze Chest',
  [CheckId.Barnes_Bomb_Bag]: 'Barnes Bomb Bag',
  [CheckId.Eldin_Field_Bomskit_Grotto_Lantern_Chest]: 'Eldin Field Bomskit Grotto Lantern Chest',
  [CheckId.City_in_The_Sky_Central_Outside_Poe_Island_Chest]:
    'City in The Sky Central Outside Poe Island Chest',
  [CheckId.STAR_Prize_2]: 'STAR Prize 2',
  [CheckId.City_in_The_Sky_West_Garden_Corner_Chest]: 'City in The Sky West Garden Corner Chest',
  [CheckId.Death_Mountain_Alcove_Chest]: 'Death Mountain Alcove Chest',
  [CheckId.North_Castle_Town_Golden_Wolf]: 'North Castle Town Golden Wolf',
  [CheckId.Forest_Temple_Second_Monkey_Under_Bridge_Chest]:
    'Forest Temple Second Monkey Under Bridge Chest',
  [CheckId.Gerudo_Desert_West_Canyon_Chest]: 'Gerudo Desert West Canyon Chest',
  [CheckId.Agitha_Male_Mantis_Reward]: 'Agitha Male Mantis Reward',
  [CheckId.Lanayru_Ice_Block_Puzzle_Cave_Chest]: 'Lanayru Ice Block Puzzle Cave Chest',
  [CheckId.City_in_The_Sky_West_Wing_Tile_Worm_Chest]: 'City in The Sky West Wing Tile Worm Chest',
  [CheckId.Fishing_Hole_Heart_Piece]: 'Fishing Hole Heart Piece',
  [CheckId.Bridge_of_Eldin_Male_Phasmid]: 'Bridge of Eldin Male Phasmid',
  [CheckId.Forest_Temple_Windless_Bridge_Chest]: 'Forest Temple Windless Bridge Chest',
  [CheckId.Zoras_Domain_Light_All_Torches_Chest]: 'Zoras Domain Light All Torches Chest',
  [CheckId.Palace_of_Twilight_West_Wing_Second_Room_Central_Chest]:
    'Palace of Twilight West Wing Second Room Central Chest',
  [CheckId.Rutelas_Blessing]: 'Rutelas Blessing',
  [CheckId.City_in_The_Sky_East_Wing_After_Dinalfos_Alcove_Chest]:
    'City in The Sky East Wing After Dinalfos Alcove Chest',
  [CheckId.Snowpeak_Cave_Ice_Poe]: 'Snowpeak Cave Ice Poe',
  [CheckId.Lakebed_Temple_Stalactite_Room_Chest]: 'Lakebed Temple Stalactite Room Chest',
  [CheckId.Temple_of_Time_Armos_Antechamber_Statue_Chest]:
    'Temple of Time Armos Antechamber Statue Chest',
  [CheckId.Cave_of_Ordeals_Floor_17_Poe]: 'Cave of Ordeals Floor 17 Poe',
  [CheckId.Arbiters_Grounds_West_Small_Chest_Behind_Block]:
    'Arbiters Grounds West Small Chest Behind Block',
  [CheckId.Temple_of_Time_Gilloutine_Chest]: 'Temple of Time Gilloutine Chest',
  [CheckId.Cats_Hide_and_Seek_Minigame]: 'Cats Hide and Seek Minigame',
  [CheckId.Goron_Mines_Entrance_Chest]: 'Goron Mines Entrance Chest',
  [CheckId.Auru_Gift_To_Fyer]: 'Auru Gift To Fyer',
  [CheckId.Snowpeak_Above_Freezard_Grotto_Poe]: 'Snowpeak Above Freezard Grotto Poe',
  [CheckId.Lake_Lantern_Cave_First_Chest]: 'Lake Lantern Cave First Chest',
  [CheckId.Flight_By_Fowl_Fifth_Platform_Chest]: 'Flight By Fowl Fifth Platform Chest',
  [CheckId.Kakariko_Watchtower_Chest]: 'Kakariko Watchtower Chest',
  [CheckId.Faron_Field_Corner_Grotto_Left_Chest]: 'Faron Field Corner Grotto Left Chest',
  [CheckId.Outside_Lanayru_Spring_Left_Statue_Chest]: 'Outside Lanayru Spring Left Statue Chest',
  [CheckId.Hidden_Village_Poe]: 'Hidden Village Poe',
  [CheckId.Arbiters_Grounds_Ghoul_Rat_Room_Chest]: 'Arbiters Grounds Ghoul Rat Room Chest',
  [CheckId.Gerudo_Desert_East_Poe]: 'Gerudo Desert East Poe',
  [CheckId.Bulblin_Camp_Small_Chest_in_Back_of_Camp]: 'Bulblin Camp Small Chest in Back of Camp',
  [CheckId.Ilia_Memory_Reward]: 'Ilia Memory Reward',
  [CheckId.Lanayru_Spring_Back_Room_Lantern_Chest]: 'Lanayru Spring Back Room Lantern Chest',
  [CheckId.Agitha_Female_Ladybug_Reward]: 'Agitha Female Ladybug Reward',
  [CheckId.Palace_of_Twilight_West_Wing_First_Room_Central_Chest]:
    'Palace of Twilight West Wing First Room Central Chest',
  [CheckId.City_in_The_Sky_Dungeon_Reward]: 'City in The Sky Dungeon Reward',
  [CheckId.Kakariko_Gorge_Owl_Statue_Sky_Character]: 'Kakariko Gorge Owl Statue Sky Character',
  [CheckId.Forest_Temple_Gale_Boomerang]: 'Forest Temple Gale Boomerang',
  [CheckId.Gerudo_Desert_Skulltula_Grotto_Chest]: 'Gerudo Desert Skulltula Grotto Chest',
  [CheckId.Forest_Temple_West_Deku_Like_Chest]: 'Forest Temple West Deku Like Chest',
  [CheckId.Agitha_Male_Stag_Beetle_Reward]: 'Agitha Male Stag Beetle Reward',
  [CheckId.Faron_Field_Male_Beetle]: 'Faron Field Male Beetle',
  [CheckId.Palace_of_Twilight_East_Wing_First_Room_North_Small_Chest]:
    'Palace of Twilight East Wing First Room North Small Chest',
  [CheckId.Kakariko_Graveyard_Male_Ant]: 'Kakariko Graveyard Male Ant',
  [CheckId.Temple_of_Time_Scales_Upper_Chest]: 'Temple of Time Scales Upper Chest',
  [CheckId.Eldin_Field_Stalfos_Grotto_Stalfos_Chest]: 'Eldin Field Stalfos Grotto Stalfos Chest',
  [CheckId.Ordon_Cat_Rescue]: 'Ordon Cat Rescue',
  [CheckId.Lakebed_Temple_Underwater_Maze_Small_Chest]:
    'Lakebed Temple Underwater Maze Small Chest',
  [CheckId.Snowpeak_Ruins_West_Cannon_Room_Corner_Chest]:
    'Snowpeak Ruins West Cannon Room Corner Chest',
  [CheckId.Lanayru_Spring_Underwater_Left_Chest]: 'Lanayru Spring Underwater Left Chest',
  [CheckId.Lake_Hylia_Bridge_Owl_Statue_Chest]: 'Lake Hylia Bridge Owl Statue Chest',
  [CheckId.Talo_Sharpshooting]: 'Talo Sharpshooting',
  [CheckId.Lakebed_Temple_Central_Room_Spire_Chest]: 'Lakebed Temple Central Room Spire Chest',
  [CheckId.Lake_Hylia_Bridge_Owl_Statue_Sky_Character]:
    'Lake Hylia Bridge Owl Statue Sky Character',
  [CheckId.Gerudo_Desert_North_Small_Chest_Before_Bulblin_Camp]:
    'Gerudo Desert North Small Chest Before Bulblin Camp',
  [CheckId.Lakebed_Temple_Chandelier_Chest]: 'Lakebed Temple Chandelier Chest',
  [CheckId.Zoras_Domain_Extinguish_All_Torches_Chest]: 'Zoras Domain Extinguish All Torches Chest',
  [CheckId.Lake_Lantern_Cave_End_Lantern_Chest]: 'Lake Lantern Cave End Lantern Chest',
  [CheckId.Temple_of_Time_Chest_Before_Darknut]: 'Temple of Time Chest Before Darknut',
  [CheckId.Snowpeak_Poe_Among_Trees]: 'Snowpeak Poe Among Trees',
  [CheckId.Agitha_Male_Pill_Bug_Reward]: 'Agitha Male Pill Bug Reward',
  [CheckId.Herding_Goats_Reward]: 'Herding Goats Reward',
  [CheckId.Gerudo_Desert_North_Peahat_Poe]: 'Gerudo Desert North Peahat Poe',
  [CheckId.Snowpeak_Ruins_Chapel_Chest]: 'Snowpeak Ruins Chapel Chest',
  [CheckId.Lakebed_Temple_Dungeon_Reward]: 'Lakebed Temple Dungeon Reward',
  [CheckId.Lake_Lantern_Cave_Sixth_Chest]: 'Lake Lantern Cave Sixth Chest',
  [CheckId.Eldin_Field_Bomb_Rock_Chest]: 'Eldin Field Bomb Rock Chest',
  [CheckId.Agitha_Male_Grasshopper_Reward]: 'Agitha Male Grasshopper Reward',
  [CheckId.Flight_By_Fowl_Top_Platform_Reward]: 'Flight By Fowl Top Platform Reward',
  [CheckId.Kakariko_Gorge_Double_Clawshot_Chest]: 'Kakariko Gorge Double Clawshot Chest',
  [CheckId.Lanayru_Field_Bridge_Poe]: 'Lanayru Field Bridge Poe',
  [CheckId.Wooden_Statue]: 'Wooden Statue',
  [CheckId.Fishing_Hole_Bottle]: 'Fishing Hole Bottle',
  [CheckId.Snowpeak_Ruins_East_Courtyard_Chest]: 'Snowpeak Ruins East Courtyard Chest',
  [CheckId.Lake_Hylia_Alcove_Poe]: 'Lake Hylia Alcove Poe',
  [CheckId.Lanayru_Field_Poe_Grotto_Right_Poe]: 'Lanayru Field Poe Grotto Right Poe',
  [CheckId.Gerudo_Desert_Owl_Statue_Sky_Character]: 'Gerudo Desert Owl Statue Sky Character',
  [CheckId.Gerudo_Desert_Owl_Statue_Chest]: 'Gerudo Desert Owl Statue Chest',
  [CheckId.Palace_of_Twilight_Central_First_Room_Chest]:
    'Palace of Twilight Central First Room Chest',
  [CheckId.Snowpeak_Ruins_Wooden_Beam_Central_Chest]: 'Snowpeak Ruins Wooden Beam Central Chest',
  [CheckId.Snowpeak_Ruins_Ball_and_Chain]: 'Snowpeak Ruins Ball and Chain',
  [CheckId.Plumm_Fruit_Balloon_Minigame]: 'Plumm Fruit Balloon Minigame',
  [CheckId.Kakariko_Gorge_Spire_Heart_Piece]: 'Kakariko Gorge Spire Heart Piece',
  [CheckId.Lakebed_Temple_Before_Deku_Toad_Underwater_Right_Chest]:
    'Lakebed Temple Before Deku Toad Underwater Right Chest',
  [CheckId.Outside_Bulblin_Camp_Poe]: 'Outside Bulblin Camp Poe',
  [CheckId.Doctors_Office_Balcony_Chest]: 'Doctors Office Balcony Chest',
  [CheckId.Outside_Lanayru_Spring_Right_Statue_Chest]: 'Outside Lanayru Spring Right Statue Chest',
  [CheckId.Upper_Zoras_River_Poe]: 'Upper Zoras River Poe',
  [CheckId.Bulblin_Camp_Poe]: 'Bulblin Camp Poe',
  [CheckId.Hyrule_Castle_East_Wing_Balcony_Chest]: 'Hyrule Castle East Wing Balcony Chest',
  [CheckId.Lake_Lantern_Cave_Seventh_Chest]: 'Lake Lantern Cave Seventh Chest',
  [CheckId.Lanayru_Spring_East_Double_Clawshot_Chest]: 'Lanayru Spring East Double Clawshot Chest',
  [CheckId.Snowpeak_Icy_Summit_Poe]: 'Snowpeak Icy Summit Poe',
  [CheckId.Outside_South_Castle_Town_Poe]: 'Outside South Castle Town Poe',
  [CheckId.Temple_of_Time_Scales_Gohma_Chest]: 'Temple of Time Scales Gohma Chest',
  [CheckId.Goron_Mines_Gor_Amato_Key_Shard]: 'Goron Mines Gor Amato Key Shard',
  [CheckId.Kakariko_Gorge_Female_Pill_Bug]: 'Kakariko Gorge Female Pill Bug',
  [CheckId.Eldin_Stockcave_Lantern_Chest]: 'Eldin Stockcave Lantern Chest',
  [CheckId.Eldin_Lantern_Cave_Lantern_Chest]: 'Eldin Lantern Cave Lantern Chest',
  [CheckId.Agitha_Female_Butterfly_Reward]: 'Agitha Female Butterfly Reward',
  [CheckId.Outside_South_Castle_Town_Female_Ladybug]: 'Outside South Castle Town Female Ladybug',
  [CheckId.Hyrule_Castle_Treasure_Room_First_Chest]: 'Hyrule Castle Treasure Room First Chest',
  [CheckId.Telma_Invoice]: 'Telma Invoice',
  [CheckId.Snowpeak_Ruins_Wooden_Beam_Northwest_Chest]:
    'Snowpeak Ruins Wooden Beam Northwest Chest',
  [CheckId.Lakebed_Temple_Before_Deku_Toad_Alcove_Chest]:
    'Lakebed Temple Before Deku Toad Alcove Chest',
  [CheckId.Eldin_Lantern_Cave_Poe]: 'Eldin Lantern Cave Poe',
  [CheckId.Kakariko_Village_Malo_Mart_Hylian_Shield]: 'Kakariko Village Malo Mart Hylian Shield',
  [CheckId.Palace_of_Twilight_East_Wing_First_Room_East_Alcove]:
    'Palace of Twilight East Wing First Room East Alcove',
  [CheckId.Bulblin_Camp_Roasted_Boar]: 'Bulblin Camp Roasted Boar',
  [CheckId.Faron_Woods_Golden_Wolf]: 'Faron Woods Golden Wolf',
  [CheckId.Jovani_60_Poe_Soul_Reward]: 'Jovani 60 Poe Soul Reward',
};

// const checkIdToNameMap: Record<number, string> = {};
const checkNameToIdMap: Record<string, CheckId> = {};

Object.keys(checkIdToNameMap).forEach(checkIdStr => {
  const checkId = parseInt(checkIdStr, 10) as CheckId;
  const checkName = checkIdToNameMap[checkId];
  if (checkName != null) {
    checkNameToIdMap[checkName] = checkId;
  }
});

export function checkIdToName(checkId: CheckId): string | undefined {
  if (Object.prototype.hasOwnProperty.call(checkIdToNameMap, checkId)) {
    return checkIdToNameMap[checkId];
  }
  return undefined;
}

export function checkNameToId(checkName: string): CheckId {
  if (Object.prototype.hasOwnProperty.call(checkNameToIdMap, checkName)) {
    return checkNameToIdMap[checkName];
  }
  return CheckId.Invalid;
}

export const alphabeticalCheckIds: number[] = Object.keys(checkNameToIdMap)
  .sort()
  .map(checkNameToId);
