name: Image
on: [workflow_call]

concurrency:
  group: image-${{ github.ref }}
  cancel-in-progress: true


defaults:
  run:
    shell: 'bash'

jobs:
  build_image:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - run: yarn --immutable
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: yarn --cwd website run prisma:generate

      - run: yarn image

      - run: node scripts/imageToRelease.mjs
        env:
          GH_TOKEN: ${{ secrets.github_token }}
