name: Tests
on: [ workflow_call ]

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        # os: [ windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn --immutable
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: yarn --cwd website run prisma:generate
      - run: yarn test:main
      - run: yarn test:preload
      # Disable renderer tests after swapping to React. The UI is still being
      # worked on, so these tests don't make sense right now anyway. Maybe
      # should bring back at some point.
      # - run: yarn test:renderer

      # I ran into problems trying to run an electron window in ubuntu due to a missing graphics server.
      # That's why this special command for Ubuntu is here
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn test:e2e
        if: matrix.os == 'ubuntu-latest'

      - run: yarn test:e2e
        if: matrix.os != 'ubuntu-latest'
